# -*- coding: utf-8 -*-
"""Question 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgJz4pFZKF8r0q-6JGNRWbWX_S62Tb5B

Stage (t): Each year of construction, t = 1, 2, 3, 4, 5

State (s): The backlog at the start of each year — i.e. the number of stations that are due but not yet built. Since at most 1 backlog is allowed, s ∈ {0, 1}

Action (x): The number of stations built in year t.

For t = 1, 2, 3, 4: x ∈ {0, 1, 2} (at most 2 per year)

For t = 5: x can be anything needed to clear all remaining demand

Variables:

g(t) = growth in subdivisions per year: 1, 2, 1, 3, 2

c(t) = cost per station: 1.0, 1.2, 1.4, 1.8, 1.7 (Million $)

Fixed cost F = $2M per year if any station is built (x > 0)

Discount factor = 0.9 per year

State Transition Function:

Backlog at end of year = stations due but unbuilt:

s(t+1) = s(t) + g(t) - x(t)

Constraints:

s(t+1) ∈ {0, 1} — backlog cannot exceed 1

x(t) ≥ 0


By year 5: s(6) = 0 (all stations must be built)

Contribution Function (Cost in year t):

C(s, x, t) = 0.9^(t-1) × [ c(t) × x(t) + F × 𝟙(x(t) > 0) ]

Where 𝟙(x > 0) = 1 if any station is built, 0 otherwise.

DP Recursion (minimization):

f(s, t) = min over x { C(s, x, t) + f(s(t+1), t+1) }

With terminal condition:

f(0, 6) = 0 — no cost after year 5 if all built
"""

import numpy as np
import pandas as pd

# ── Problem Parameters ───────────────────────────────────────────────────────
growth       = {1: 1, 2: 2, 3: 1, 4: 3, 5: 2}        # subdivisions per year
cost_per_stn = {1: 1.0, 2: 1.2, 3: 1.4, 4: 1.8, 5: 1.7}  # Million $ per station
fixed_cost   = 2.0                                      # Million $ if any station built
discount     = 0.9
max_build    = 2       # max stations per year (except year 5)
max_backlog  = 1       # max allowed backlog

# ── DP Tables ────────────────────────────────────────────────────────────────
# f[t][s]     = min cost from year t onwards given backlog s
# x_opt[t][s] = optimal number of stations to build at year t given backlog s

INF   = float('inf')
f     = {t: {} for t in range(1, 7)}   # t=6 is terminal
x_opt = {t: {} for t in range(1, 6)}

# ── Terminal Condition: after year 5, backlog must be 0 ─────────────────────
f[6][0] = 0.0      # all stations built, no cost
f[6][1] = INF      # backlog remaining = infeasible

# ── Backward Induction ───────────────────────────────────────────────────────
for t in range(5, 0, -1):
    g        = growth[t]
    c        = cost_per_stn[t]
    disc     = discount ** (t - 1)
    max_x    = max_build if t < 5 else 20   # year 5 has no build limit

    for s in range(0, max_backlog + 1):     # s ∈ {0, 1}

        best_cost = INF
        best_x    = None

        for x in range(0, max_x + 1):

            # state transition
            s_next = s + g - x

            # feasibility checks
            if s_next < 0:
                continue   # built more than needed
            if t < 5 and s_next > max_backlog:
                continue   # backlog would exceed limit
            if t == 5 and s_next != 0:
                continue   # year 5: must clear all backlog

            # cost this year (discounted)
            if x > 0:
                year_cost = disc * (c * x + fixed_cost)
            else:
                year_cost = 0.0

            future_cost = f[t + 1].get(s_next, INF)
            if future_cost == INF:
                continue

            total = year_cost + future_cost

            if total < best_cost:
                best_cost = total
                best_x    = x

        f[t][s]     = best_cost
        x_opt[t][s] = best_x

# ── Trace Optimal Path ───────────────────────────────────────────────────────
print("=" * 75)
print("       METRO STATION CONSTRUCTION — OPTIMAL DP SOLUTION")
print("=" * 75)

s          = 0     # start with zero backlog
total_cost = 0.0
results    = []

for t in range(1, 6):
    g      = growth[t]
    c      = cost_per_stn[t]
    disc   = discount ** (t - 1)
    x      = x_opt[t].get(s, 0)
    s_next = s + g - x

    if x > 0:
        year_cost = disc * (c * x + fixed_cost)
    else:
        year_cost = 0.0

    total_cost += year_cost

    results.append({
        "Year (t)"              : t,
        "Backlog Start (s)"     : s,
        "Growth (g)"            : g,
        "Stations Built (x)"    : x,
        "Backlog End (s_next)"  : s_next,
        "Fixed Cost Applied"    : "Yes" if x > 0 else "No",
        "Year Cost (M$)"        : round(year_cost, 4),
        "Cumulative Cost (M$)"  : round(total_cost, 4)
    })

    s = s_next

df = pd.DataFrame(results)
print(df.to_string(index=False))
print("=" * 75)
print(f"  TOTAL MINIMUM CONSTRUCTION COST: ${total_cost:.4f} Million")
print("=" * 75)

# ── Full DP Table ─────────────────────────────────────────────────────────────
print("\n")
print("=" * 50)
print("  FULL DP TABLE  f(t, s) = min cost from year t")
print("=" * 50)
rows = []
for t in range(1, 6):
    for s in range(0, max_backlog + 1):
        rows.append({
            "Year (t)"      : t,
            "Backlog (s)"   : s,
            "f(t,s) (M$)"   : round(f[t].get(s, INF), 4),
            "Optimal x"     : x_opt[t].get(s, '-')
        })
df2 = pd.DataFrame(rows)
print(df2.to_string(index=False))

